# Generated by Django 6.0.7 on 2026-07-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='visits.appointment'),
        ),
    ]
