# Generated by Django 6.0.7 on 2026-08-19 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_address_customuser_profile_picture_and_more'),
        ('visits', '0005_appointment_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.hospital'),
        ),
    ]
