from rest_framework import serializers
from accounts.models import Patient


# PatientSerializer is responsible for converting Patient model instances
# into JSON format for API responses and validating incoming JSON data
# before updating the Patient model.
#
# This serializer also exposes selected information from the related
# CustomUser model, allowing the frontend to receive both patient-specific
# and user-specific information in a single API response.
class PatientSerializer(serializers.ModelSerializer):

    # SerializerMethodField creates a read-only field whose value is
    # generated by a custom method instead of being read directly from
    # the Patient model.
    #
    # Since the patient's full name is stored in the related CustomUser
    # model rather than the Patient model, this field retrieves it dynamically.
    full_name = serializers.SerializerMethodField()

    # Returns the email address of the authenticated patient.
    #
    # The email belongs to the related CustomUser model, making this
    # another computed field instead of a database field on Patient.
    email = serializers.SerializerMethodField()

    class Meta:
        # Specifies the model that this serializer represents.
        model = Patient

        # Defines all fields that will be included in API requests
        # and responses.
        #
        # The serializer combines:
        # - Computed fields (full_name, email)
        # - Patient profile fields
        # - System-generated fields
        fields = (
            "id",
            "full_name",
            "email",
            "date_of_birth",
            "gender",
            "blood_group",
            "emergency_contact",
            "address",
            "created_at",
        )

        # These fields are managed automatically by the system and
        # therefore cannot be modified through API requests.
        #
        # - id is automatically generated by Django.
        # - created_at records when the patient profile was created.
        read_only_fields = ["id", "created_at"]

    # Returns the patient's full name.
    #
    # The obj parameter represents the current Patient instance being
    # serialized. Because each Patient has a One-to-One relationship
    # with CustomUser, we can access the related user object through
    # obj.user and call Django's built-in get_full_name() method.
    #
    # This approach avoids storing duplicate name information in the
    # Patient model, helping maintain database normalization.
    def get_full_name(self, obj):
        return obj.user.get_full_name()

    # Returns the patient's email address from the related CustomUser.
    #
    # Instead of duplicating the email in the Patient model, the serializer
    # retrieves it directly from the associated user account, ensuring
    # consistency across the system.
    def get_email(self, obj):
        return obj.user.email