import { useEffect, useState } from "react";
import {
  FaBell,
  FaCalendarAlt,
  FaCheckCircle,
  FaClock,
  FaExclamationCircle,
  FaHeartbeat,
  FaPills,
  FaRedo,
  FaTrash,
} from "react-icons/fa";

import {
  getNotifications,
  markNotificationAsRead,
  deleteNotification,
} from "../../services/notificationService";

/**
 * Notifications Page
 *
 * Displays notifications generated by the PulsePath system.
 *
 * Users can:
 * - View their notifications
 * - See unread notification count
 * - Mark individual notifications as read
 * - Mark all unread notifications as read
 * - Delete notifications
 * - Refresh the notification list
 *
 * Notifications can relate to:
 * - Medication reminders
 * - Appointments
 * - Follow-ups
 * - Missed doses
 * - General system updates
 */
function Notifications() {
  // Stores all notifications returned from the API.
  const [notifications, setNotifications] = useState([]);

  // Controls the loading state while notifications are being fetched.
  const [loading, setLoading] = useState(true);

  // Stores an error message to display when an API operation fails.
  const [error, setError] = useState("");

  /**
   * Load notifications when the component is first rendered.
   */
  useEffect(() => {
    loadNotifications();
  }, []);

  /**
   * Fetch the user's notifications from the backend.
   */
  const loadNotifications = async () => {
    try {
      // Show the loading state and clear previous errors.
      setLoading(true);
      setError("");

      // Request notifications from the API.
      const data = await getNotifications();

      console.log("NOTIFICATIONS API RESPONSE:", data);

      // Make sure the state always contains an array.
      setNotifications(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error("Failed to load notifications:", err);

      // Display a user-friendly error message.
      setError("Failed to load notifications.");
    } finally {
      // Stop the loading indicator regardless of success or failure.
      setLoading(false);
    }
  };

  /**
   * Mark one notification as read.
   *
   * The backend is updated first, then the local state is
   * updated so the UI immediately reflects the change.
   */
  const handleMarkAsRead = async (id) => {
    try {
      // Tell the backend to mark the notification as read.
      await markNotificationAsRead(id);

      // Update only the notification that was marked as read.
      setNotifications((previous) =>
        previous.map((notification) =>
          notification.id === id
            ? { ...notification, is_read: true }
            : notification
        )
      );
    } catch (err) {
      console.error("Failed to mark notification as read:", err);

      // Display an error if the update fails.
      setError("Failed to update notification.");
    }
  };

  /**
   * Delete a notification.
   *
   * The notification is removed from the backend and then
   * removed from the local state.
   */
  const handleDelete = async (id) => {
    try {
      // Delete the notification from the backend.
      await deleteNotification(id);

      // Remove the deleted notification from the current state.
      setNotifications((previous) =>
        previous.filter((notification) => notification.id !== id)
      );
    } catch (err) {
      console.error("Failed to delete notification:", err);

      // Display an error if deletion fails.
      setError("Failed to delete notification.");
    }
  };

  /**
   * Mark every currently unread notification as read.
   *
   * Promise.all allows all individual API requests to be
   * processed together before updating the UI.
   */
  const handleMarkAllAsRead = async () => {
    try {
      // Find only notifications that have not yet been read.
      const unreadNotifications = notifications.filter(
        (notification) => !notification.is_read
      );

      // Send a mark-as-read request for each unread notification.
      await Promise.all(
        unreadNotifications.map((notification) =>
          markNotificationAsRead(notification.id)
        )
      );

      // Once all requests succeed, mark every local notification
      // as read so the UI reflects the backend state.
      setNotifications((previous) =>
        previous.map((notification) => ({
          ...notification,
          is_read: true,
        }))
      );
    } catch (err) {
      console.error("Failed to mark all as read:", err);

      // Display an error if any of the requests fail.
      setError("Failed to mark all notifications as read.");
    }
  };

  /**
   * Return the appropriate icon based on notification type.
   */
  const getNotificationIcon = (type) => {
    switch (type) {
      // Medication-related notification.
      case "MEDICATION":
        return <FaPills />;

      // Appointment-related notification.
      case "APPOINTMENT":
        return <FaCalendarAlt />;

      // Follow-up or recovery-related notification.
      case "FOLLOW_UP":
        return <FaHeartbeat />;

      // Missed medication dose notification.
      case "MISSED_DOSE":
        return <FaExclamationCircle />;

      // General notification or unknown type.
      case "GENERAL":
      default:
        return <FaBell />;
    }
  };

  /**
   * Return Bootstrap text/background classes based on
   * the notification type.
   */
  const getNotificationClass = (type) => {
    switch (type) {
      // Medication notifications use the primary styling.
      case "MEDICATION":
        return "text-primary bg-primary-subtle";

      // Appointment notifications use success styling.
      case "APPOINTMENT":
        return "text-success bg-success-subtle";

      // Follow-up notifications use warning styling.
      case "FOLLOW_UP":
        return "text-warning bg-warning-subtle";

      // Missed-dose notifications use danger styling.
      case "MISSED_DOSE":
        return "text-danger bg-danger-subtle";

      // General or unknown notifications use secondary styling.
      case "GENERAL":
      default:
        return "text-secondary bg-secondary-subtle";
    }
  };

  /**
   * Convert notification type values into readable labels.
   *
   * Example:
   * "MISSED_DOSE" -> "Missed Dose"
   */
  const formatNotificationType = (type) => {
    return type
      .replaceAll("_", " ")
      .toLowerCase()
      .replace(/\b\w/g, (letter) => letter.toUpperCase());
  };

  /**
   * Convert the notification timestamp into a readable
   * local date and time.
   */
  const formatDate = (date) => {
    return new Date(date).toLocaleString([], {
      dateStyle: "medium",
      timeStyle: "short",
    });
  };

  // Calculate the number of unread notifications.
  const unreadCount = notifications.filter(
    (notification) => !notification.is_read
  ).length;

  /**
   * Display a loading screen while notifications
   * are being retrieved.
   */
  if (loading) {
    return (
      <div className="container-fluid py-4">
        <div className="text-center py-5">
          <div
            className="spinner-border text-primary"
            role="status"
          >
            <span className="visually-hidden">
              Loading...
            </span>
          </div>

          <p className="text-muted mt-3">
            Loading notifications...
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="container-fluid py-4">

      {/* =========================
          PAGE HEADER
          Displays the page title,
          unread count, refresh button,
          and mark-all-as-read button.
      ========================== */}

      <div className="d-flex flex-wrap justify-content-between align-items-center mb-4">

        <div>
          <div className="d-flex align-items-center gap-2">

            <h2 className="fw-bold mb-1">
              Notifications
            </h2>

            {/* Display the number of unread
                notifications when there are any. */}
            {unreadCount > 0 && (
              <span className="badge bg-primary rounded-pill">
                {unreadCount} new
              </span>
            )}

          </div>

          <p className="text-muted mb-0">
            Stay updated with your medications, appointments,
            follow-ups and recovery.
          </p>
        </div>

        <div className="d-flex gap-2 mt-3 mt-md-0">

          {/* Reload notifications from the backend. */}
          <button
            className="btn btn-outline-secondary"
            onClick={loadNotifications}
          >
            <FaRedo className="me-2" />
            Refresh
          </button>

          {/* Only display this button when there are
              unread notifications. */}
          {unreadCount > 0 && (
            <button
              className="btn btn-primary"
              onClick={handleMarkAllAsRead}
            >
              <FaCheckCircle className="me-2" />
              Mark all as read
            </button>
          )}

        </div>
      </div>

      {/* =========================
          ERROR ALERT
          Displays errors generated
          by API operations.
      ========================== */}

      {error && (
        <div
          className="alert alert-danger d-flex justify-content-between align-items-center"
          role="alert"
        >
          <span>{error}</span>

          {/* Close the error alert. */}
          <button
            className="btn-close"
            onClick={() => setError("")}
          />
        </div>
      )}

      {/* =========================
          EMPTY STATE
          Displayed when there are
          no notifications.
      ========================== */}

      {notifications.length === 0 ? (
        <div className="card border-0 shadow-sm">
          <div className="card-body text-center py-5">

            {/* Notification icon. */}
            <div
              className="rounded-circle bg-primary-subtle text-primary d-flex align-items-center justify-content-center mx-auto mb-3"
              style={{
                width: "80px",
                height: "80px",
                fontSize: "30px",
              }}
            >
              <FaBell />
            </div>

            <h4 className="fw-bold">
              You're all caught up!
            </h4>

            <p className="text-muted mb-0">
              You don't have any notifications right now.
            </p>

          </div>
        </div>
      ) : (

        <div className="row g-4">

          {/* =========================
              MAIN NOTIFICATIONS
              Displays the notification
              cards.
          ========================== */}

          <div className="col-lg-8">

            <div className="card border-0 shadow-sm">

              {/* Notifications section heading. */}
              <div className="card-header bg-white border-0 pt-4 px-4">

                <h5 className="fw-bold mb-1">
                  Recent notifications
                </h5>

                <p className="text-muted small mb-0">
                  Your latest PulsePath updates
                </p>

              </div>

              <div className="card-body px-4">

                {/* Render each notification as an individual card. */}
                {notifications.map((notification) => (

                  <div
                    key={notification.id}
                    className={`p-3 mb-3 rounded-4 border ${
                      notification.is_read
                        ? "bg-white"
                        : "bg-light border-primary-subtle"
                    }`}
                  >

                    <div className="d-flex gap-3">

                      {/* =========================
                          NOTIFICATION ICON
                          Icon and styling depend
                          on notification type.
                      ========================== */}

                      <div
                        className={`rounded-3 d-flex align-items-center justify-content-center flex-shrink-0 ${getNotificationClass(
                          notification.notification_type
                        )}`}
                        style={{
                          width: "52px",
                          height: "52px",
                          fontSize: "20px",
                        }}
                      >
                        {getNotificationIcon(
                          notification.notification_type
                        )}
                      </div>

                      {/* =========================
                          NOTIFICATION CONTENT
                      ========================== */}

                      <div className="flex-grow-1">

                        <div className="d-flex flex-wrap justify-content-between gap-2">

                          <div className="d-flex align-items-center gap-2">

                            {/* Notification title. */}
                            <h6 className="fw-bold mb-0">
                              {notification.title}
                            </h6>

                            {/* Show "New" only for unread notifications. */}
                            {!notification.is_read && (
                              <span className="badge bg-primary rounded-pill">
                                New
                              </span>
                            )}

                          </div>

                          {/* Display the formatted notification type. */}
                          <span
                            className={`badge ${getNotificationClass(
                              notification.notification_type
                            )}`}
                          >
                            {formatNotificationType(
                              notification.notification_type
                            )}
                          </span>

                        </div>

                        {/* Notification message. */}
                        <p className="text-muted mt-2 mb-2">
                          {notification.message}
                        </p>

                        <div className="d-flex flex-wrap justify-content-between align-items-center">

                          {/* Notification creation date and time. */}
                          <small className="text-muted">
                            <FaClock className="me-1" />
                            {formatDate(notification.created_at)}
                          </small>

                          <div className="d-flex gap-2 mt-2 mt-sm-0">

                            {/* Show the mark-as-read button only
                                when the notification is unread. */}
                            {!notification.is_read && (
                              <button
                                className="btn btn-sm btn-outline-primary"
                                onClick={() =>
                                  handleMarkAsRead(
                                    notification.id
                                  )
                                }
                              >
                                <FaCheckCircle className="me-1" />
                                Mark as read
                              </button>
                            )}

                            {/* Delete the notification. */}
                            <button
                              className="btn btn-sm btn-outline-danger"
                              onClick={() =>
                                handleDelete(notification.id)
                              }
                            >
                              <FaTrash />
                            </button>

                          </div>

                        </div>

                      </div>

                    </div>

                  </div>

                ))}

              </div>
            </div>

          </div>

          {/* =========================
              NOTIFICATION SUMMARY
              Displays total, unread,
              and read notification counts.
          ========================== */}

          <div className="col-lg-4">

            <div className="card border-0 shadow-sm mb-4">

              <div className="card-body p-4">

                {/* Summary heading. */}
                <div className="d-flex align-items-center gap-3 mb-4">

                  <div
                    className="rounded-circle bg-primary-subtle text-primary d-flex align-items-center justify-content-center"
                    style={{
                      width: "52px",
                      height: "52px",
                    }}
                  >
                    <FaBell />
                  </div>

                  <div>
                    <h5 className="fw-bold mb-0">
                      Notification center
                    </h5>

                    <small className="text-muted">
                      PulsePath updates
                    </small>
                  </div>

                </div>

                {/* Total number of notifications. */}
                <div className="d-flex justify-content-between py-2 border-bottom">
                  <span className="text-muted">
                    Total
                  </span>

                  <strong>
                    {notifications.length}
                  </strong>
                </div>

                {/* Number of unread notifications. */}
                <div className="d-flex justify-content-between py-2 border-bottom">
                  <span className="text-muted">
                    Unread
                  </span>

                  <strong className="text-primary">
                    {unreadCount}
                  </strong>
                </div>

                {/* Number of read notifications. */}
                <div className="d-flex justify-content-between py-2">
                  <span className="text-muted">
                    Read
                  </span>

                  <strong>
                    {notifications.length - unreadCount}
                  </strong>
                </div>

              </div>

            </div>

            {/* =========================
                REMINDER CARD
                Provides a short reminder
                about staying engaged with
                PulsePath notifications.
            ========================== */}

            <div className="card border-0 shadow-sm">

              <div className="card-body p-4">

                <div className="d-flex align-items-center gap-3 mb-3">

                  <div
                    className="rounded-3 bg-success-subtle text-success d-flex align-items-center justify-content-center"
                    style={{
                      width: "48px",
                      height: "48px",
                    }}
                  >
                    <FaHeartbeat />
                  </div>

                  <div>
                    <h6 className="fw-bold mb-0">
                      Stay on track
                    </h6>

                    <small className="text-muted">
                      Your recovery journey
                    </small>
                  </div>

                </div>

                <p className="text-muted small mb-0">
                  Keep an eye on your notifications for
                  medication reminders, appointments and
                  recovery updates.
                </p>

              </div>

            </div>

          </div>

        </div>
      )}

    </div>
  );
}

export default Notifications;

