# Generated by Django 6.0.7 on 2026-07-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('medication_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='treatment.medicationschedule')),
            ],
        ),
    ]
