# Generated by Django 6.0.7 on 2026-07-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor'),
        ('treatment', '0002_medicationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=10)),
                ('description', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('doctor_response', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_report', to='treatment.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_report', to='accounts.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_report', to='treatment.prescription')),
            ],
        ),
    ]
