# Generated by Django 6.0.7 on 2026-07-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
