# Generated by Django 6.0.7 on 2026-07-28 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor'),
        ('treatment', '0003_sideeffectreport'),
        ('visits', '0004_visit_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_level', models.PositiveIntegerField(help_text='Pain level on a scale of 0 to 10')),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('feeling_better', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('improvement_percentage', models.PositiveIntegerField(blank=True, help_text='Recovery improvement percentage(0-100)', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_progress', to='accounts.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_progress', to='visits.visit')),
            ],
        ),
    ]
