# Generated by Django 6.0.7 on 2026-07-29 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_recoveryprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoveryprogress',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'Recovery Progress', 'verbose_name_plural': 'Recovery Progress'},
        ),
        migrations.AddField(
            model_name='recoveryprogress',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='Example: 120/80 mmHg', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recoveryprogress',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Heart rate in beats per minute', null=True),
        ),
        migrations.AddField(
            model_name='recoveryprogress',
            name='mobility_status',
            field=models.CharField(blank=True, help_text='Example: Bedridden, Walking with support, Independent', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recoveryprogress',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoveryprogress',
            name='oxygen_saturation',
            field=models.PositiveIntegerField(blank=True, help_text='SpO₂ percentage', null=True),
        ),
        migrations.AddField(
            model_name='recoveryprogress',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_recovery_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoveryprogress',
            name='recovery_stage',
            field=models.CharField(choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('DECLINING', 'Declining'), ('RECOVERED', 'Recovered')], default='STABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='recoveryprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recoveryprogress',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recoveryprogress',
            name='body_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recoveryprogress',
            name='improvement_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Recovery improvement percentage (0-100)', null=True),
        ),
    ]
