# Generated by Django 6.0.7 on 2026-07-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_alter_recoveryprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoveryprogress',
            options={},
        ),
        migrations.RemoveField(
            model_name='recoveryprogress',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='recoveryprogress',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='recoveryprogress',
            name='mobility_status',
        ),
        migrations.RemoveField(
            model_name='recoveryprogress',
            name='next_review_date',
        ),
        migrations.RemoveField(
            model_name='recoveryprogress',
            name='oxygen_saturation',
        ),
        migrations.RemoveField(
            model_name='recoveryprogress',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='recoveryprogress',
            name='recovery_stage',
        ),
        migrations.RemoveField(
            model_name='recoveryprogress',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recoveryprogress',
            name='weight',
        ),
        migrations.AlterField(
            model_name='recoveryprogress',
            name='body_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recoveryprogress',
            name='improvement_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Recovery improvement percentage(0-100)', null=True),
        ),
    ]
