# Generated by Django 6.0.7 on 2026-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_alter_recoveryprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
