# Generated by Django 6.0.7 on 2026-08-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_address_customuser_profile_picture_and_more'),
        ('treatment', '0007_recoveryprogress_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_medications', to='accounts.hospital')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_availability', to='treatment.medication')),
            ],
            options={
                'unique_together': {('hospital', 'medication')},
            },
        ),
    ]
