# Generated by Django 6.0.7 on 2026-08-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0008_hospitalmedication'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryprogress',
            name='doctor_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoveryprogress',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
