# Generated by Django 6.0.7 on 2026-08-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MEDICATION', 'Medication Reminder'), ('APPOINTMENT', 'Appointment Reminder'), ('FOLLOW_UP', 'Follow-up Reminder'), ('MISSED_DOSE', 'Missed Dose Alert'), ('SIDE_EFFECT', 'Side Effect Update'), ('RECOVERY', 'Recovery Update'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=20),
        ),
    ]
