# Generated by Django 6.0.7 on 2026-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MEDICATION', 'Medication Reminder'), ('APPOINTMENT', 'Appointment Reminder'), ('FOLLOW_UP', 'Follow-up Reminder'), ('MISSED_DOSE', 'Missed Dose Alert'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=20),
        ),
    ]
