# Generated by Django 6.0.7 on 2026-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
