from .treatment import TreatmentListCreateView
from .prescription import PrescriptionListCreateView, PrescriptionDetailView
from .medication import MedicationListCreateView, MedicationDetailView
from .medication_schedule import MedicationScheduleListCreateView
from .medication_log import MedicationLogListCreateView